# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lui/repos/image_to_ascii

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lui/repos/image_to_ascii

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lui/repos/image_to_ascii/CMakeFiles /home/lui/repos/image_to_ascii//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lui/repos/image_to_ascii/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_to_ascii

# Build rule for target.
image_to_ascii: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_to_ascii
.PHONY : image_to_ascii

# fast build rule for target.
image_to_ascii/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/build
.PHONY : image_to_ascii/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/main.cpp.s
.PHONY : main.cpp.s

src/ascii_to_image.o: src/ascii_to_image.cpp.o
.PHONY : src/ascii_to_image.o

# target to build an object file
src/ascii_to_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/ascii_to_image.cpp.o
.PHONY : src/ascii_to_image.cpp.o

src/ascii_to_image.i: src/ascii_to_image.cpp.i
.PHONY : src/ascii_to_image.i

# target to preprocess a source file
src/ascii_to_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/ascii_to_image.cpp.i
.PHONY : src/ascii_to_image.cpp.i

src/ascii_to_image.s: src/ascii_to_image.cpp.s
.PHONY : src/ascii_to_image.s

# target to generate assembly for a file
src/ascii_to_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/ascii_to_image.cpp.s
.PHONY : src/ascii_to_image.cpp.s

src/image_to_ascii.o: src/image_to_ascii.cpp.o
.PHONY : src/image_to_ascii.o

# target to build an object file
src/image_to_ascii.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/image_to_ascii.cpp.o
.PHONY : src/image_to_ascii.cpp.o

src/image_to_ascii.i: src/image_to_ascii.cpp.i
.PHONY : src/image_to_ascii.i

# target to preprocess a source file
src/image_to_ascii.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/image_to_ascii.cpp.i
.PHONY : src/image_to_ascii.cpp.i

src/image_to_ascii.s: src/image_to_ascii.cpp.s
.PHONY : src/image_to_ascii.s

# target to generate assembly for a file
src/image_to_ascii.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_to_ascii.dir/build.make CMakeFiles/image_to_ascii.dir/src/image_to_ascii.cpp.s
.PHONY : src/image_to_ascii.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_to_ascii"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ascii_to_image.o"
	@echo "... src/ascii_to_image.i"
	@echo "... src/ascii_to_image.s"
	@echo "... src/image_to_ascii.o"
	@echo "... src/image_to_ascii.i"
	@echo "... src/image_to_ascii.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

